### ISSUE TITLE
How can I receive a callback when Swrve encounters an error?

### ISSUE THREAD

**Issue by ZakTaccardi** [Swrve/swrve-android-sdk#265] opened 2017-08-29 15:31 UTC
I want to load an attribute asynchronously (`Single<String>`). I want to delay the emission of this `String` attribute until one of the following conditions are met:

1. resources are successfully updated
2. an error occurs preventing the initial update of resources from succeeding (ex: user has no network connection)

number 1 can be achieved with `SwrveSDK.setResourceListener(listener)`, but how can I achieve number 2?

**Comment by oisin** [comment] 2017-08-29 20:00
Hi @ZakTaccardi, thanks for the issue. We do not reflect network errors back to the app from the SDK - this is by design to allow the SDK to manage its behaviour during periods of occasional connectivity. If the resource is not available, the resource will have the default value, which you can detect.

**Comment by ZakTaccardi** [comment] 2017-08-29 21:41
Let me explain our use case (hopefully) more clearly.

I'm launching *directly* into an activity that requires a swrve resource. I want to avoid the scenario where the default value is almost *always* used for first time users due to concurrency issues.

1. Activity is launched
2. Swrve makes network call to update resources (has not yet completed)
3. Activity attempts to load swrve resource, but default value is returned
4. Swrve resources are updated.

We need to know when Swrve has failed to make its initial update, so we can then use the default value.

**Comment by Sergio-Mira** [comment] 2017-10-10 13:25
Would it make sense to call the same resource listener when there is a connectivity error when loading resources? That could lave you in two states:
- No resources had been cached, resource manager is empty. Use app default.
- Resources had been cached and the value can be obtained through the Resource Manager.

Alternatively another method could be added to the listener to inform of an error.

**Comment by Sergio-Mira** [comment] 2019-04-08 16:04
Closing this issue as there hasn't been any activity recently. Please open a new issue if you need to.

**Closed as completed by Sergio-Mira** 2019-04-08 16:04 UTC
Labels: enhancement
