### ISSUE TITLE
Swrve is crashing with NoSuchFieldException: PUBLIC

### ISSUE THREAD

**Issue by vovkab** [Swrve/swrve-android-sdk#290] opened 2019-08-09 20:44 UTC
Recently we start seeing a lot of swrve crashes:

Version:
com.swrve.sdk.android:swrve-firebase:6.1.1

Stacktrace:

```
Caused by java.lang.AssertionError: java.lang.NoSuchFieldException: PUBLIC
       at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.(TypeAdapters.java:792)
       at com.google.gson.internal.bind.TypeAdapters$30.create + 818(TypeAdapters.java:818)
       at com.google.gson.Gson.getAdapter + 458(Gson.java:458)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField + 117(ReflectiveTypeAdapterFactory.java:117)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields + 166(ReflectiveTypeAdapterFactory.java:166)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create + 102(ReflectiveTypeAdapterFactory.java:102)
       at com.google.gson.Gson.getAdapter + 458(Gson.java:458)
       at com.google.gson.Gson.fromJson + 926(Gson.java:926)
       at com.google.gson.Gson.fromJson + 892(Gson.java:892)
       at com.google.gson.Gson.fromJson + 841(Gson.java:841)
       at com.google.gson.Gson.fromJson + 813(Gson.java:813)
       at com.swrve.sdk.notifications.model.SwrveNotification.fromJson + 21(SwrveNotification.java:21)
       at com.swrve.sdk.SwrveNotificationBuilder.parseBundle + 138(SwrveNotificationBuilder.java:138)
       at com.swrve.sdk.SwrveNotificationBuilder.build + 66(SwrveNotificationBuilder.java:66)
       at com.swrve.sdk.SwrvePushServiceManager.processNotification + 93(SwrvePushServiceManager.java:93)
       at com.swrve.sdk.SwrvePushServiceManager.processMessage + 33(SwrvePushServiceManager.java:33)
       at com.swrve.sdk.SwrvePushServiceDefaultJobIntentService.onHandleWork + 11(SwrvePushServiceDefaultJobIntentService.java:11)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground + 392(JobIntentService.java:392)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground + 383(JobIntentService.java:383)
       at android.os.AsyncTask$2.call + 333(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run + 266(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1162(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 636(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run + 764(Thread.java:764)
```

**Comment by davidbreenwex** [comment] 2019-08-12 09:04
Hi @vovkab,

I've seen this type of error in the past and it is usually due to the proguard rules being too restrictive.
Are you able to reproduce the issue?

**Comment by vovkab** [comment] 2019-08-12 18:13
I would assume swrve library should be shipping with it's own proguard consumer rules, since we don't know what swrve library may need to keep internally.

Anyway, we do use gson in our app and we have this rule to keep the annotation:

```
-keepclasseswithmembers class * {
    @com.google.gson.annotations.SerializedName *;
}
```

Could it be that swrve notifications are actually missing the field in payload?

**Comment by davidbreenwex** [comment] 2019-08-23 11:46
Hi @vovkab,

Can you please add this to your proguard config:

-keepclassmembernames public class com.swrve.sdk.** { 
<fields>; 
}

I've seen the same error being fixed by adding this in the past. 

Thanks, 
David

**Comment by davidbreenwex** [comment] 2019-11-20 14:10
Hi @vokab, 

Just wanted to check back in here. 
Did the above fix the issue for you?

Thanks, 
David

**Comment by davidbreenwex** [comment] 2020-03-11 09:34
Hi @vovkab,

I'm just closing this issue off for now as it has been inactive for a while. 
Let me know if you continue to have any problems, 

Best, 
David

**Closed as completed by davidbreenwex** 2020-03-11 09:34 UTC
